services:
  - type: web
    name: company-info-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
