services:
  - type: web
    name: company-scraper
    env: python
    buildCommand: "pip install -r requirements.txt && python -m playwright install"
    startCommand: "streamlit run app.py --server.port=$PORT"
    plan: free
    envVars:
      - key: PORT
        value: 10000
